<a href="https://colab.research.google.com/github/YYM89/MSSP607/blob/main/Assignment5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [ ]:
appl = pd.read_csv('/content/drive/MyDrive/MSSP607/Data/aapl.csv')
appl
amzn = pd.read_csv('/content/drive/MyDrive/MSSP607/Data/amzn.csv')
amzn
fb = pd.read_csv('/content/drive/MyDrive/MSSP607/Data/fb.csv')
fb
goog = pd.read_csv('/content/drive/MyDrive/MSSP607/Data/goog.csv')
goog
nflx = pd.read_csv('/content/drive/MyDrive/MSSP607/Data/nflx.csv')
nflx

           date    open      high       low    close    volume
0    2018-01-02  196.10  201.6500  195.4200  201.070  10966889
1    2018-01-03  202.05  206.2100  201.5000  205.050   8591369
2    2018-01-04  206.20  207.0500  204.0006  205.630   6029616
3    2018-01-05  207.25  210.0200  205.5900  209.990   7033240
4    2018-01-08  210.02  212.5000  208.4400  212.050   5580178
..          ...     ...       ...       ...      ...       ...
246  2018-12-24  242.00  250.6500  233.6800  233.880   9547616
247  2018-12-26  233.92  254.5000  231.2300  253.670  14402735
248  2018-12-27  250.11  255.5900  240.1000  255.565  12235217
249  2018-12-28  257.94  261.9144  249.8000  256.080  10987286
250  2018-12-31  260.16  270.1001  260.0000  267.660  13508920

[251 rows x 6 columns]

In [ ]:
appl['ticker'] = 'AAPL'
amzn['ticker'] = 'AMZN'
fb['ticker'] = 'FB'
goog['ticker'] = 'GOOG'
nflx['ticker'] = 'NFLX'

display(appl.head())
display(amzn.head())
display(fb.head())
display(goog.head())
display(nflx.head())

         date      open      high       low     close    volume ticker
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934   AAPL
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899   AAPL
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597   AAPL
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018   AAPL
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766   AAPL

         date     open     high      low    close   volume ticker
0  2018-01-02  1172.00  1190.00  1170.51  1189.01  2694494   AMZN
1  2018-01-03  1188.30  1205.49  1188.30  1204.20  3108793   AMZN
2  2018-01-04  1205.00  1215.87  1204.66  1209.59  3022089   AMZN
3  2018-01-05  1217.51  1229.14  1210.00  1229.14  3544743   AMZN
4  2018-01-08  1236.00  1253.08  1232.03  1246.87  4279475   AMZN

         date    open    high       low   close    volume ticker
0  2018-01-02  177.68  181.58  177.5500  181.42  18151903     FB
1  2018-01-03  181.88  184.78  181.3300  184.67  16886563     FB
2  2018-01-04  184.90  186.21  184.0996  184.33  13880896     FB
3  2018-01-05  185.59  186.90  184.9300  186.85  13574535     FB
4  2018-01-08  187.20  188.90  186.3300  188.28  17994726     FB

         date     open     high      low    close   volume ticker
0  2018-01-02  1048.34  1066.94  1045.23  1065.00  1237564   GOOG
1  2018-01-03  1064.31  1086.29  1063.21  1082.48  1430170   GOOG
2  2018-01-04  1088.00  1093.57  1084.00  1086.40  1004605   GOOG
3  2018-01-05  1094.00  1104.25  1092.00  1102.23  1279123   GOOG
4  2018-01-08  1102.23  1111.27  1101.62  1106.94  1047603   GOOG

         date    open    high       low   close    volume ticker
0  2018-01-02  196.10  201.65  195.4200  201.07  10966889   NFLX
1  2018-01-03  202.05  206.21  201.5000  205.05   8591369   NFLX
2  2018-01-04  206.20  207.05  204.0006  205.63   6029616   NFLX
3  2018-01-05  207.25  210.02  205.5900  209.99   7033240   NFLX
4  2018-01-08  210.02  212.50  208.4400  212.05   5580178   NFLX

In [ ]:
all_stocks = pd.concat([appl, amzn, fb, goog, nflx])
display(all_stocks.head())

         date      open      high       low     close    volume ticker
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934   AAPL
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899   AAPL
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597   AAPL
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018   AAPL
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766   AAPL

In [ ]:
all_stocks.to_csv('/content/drive/MyDrive/MSSP607/Data/faanf.csv', index=False)

In [ ]:
all_stocks['date'] = pd.to_datetime(all_stocks['date'])
all_stocks['volume'] = all_stocks['volume'].astype(int)

display(all_stocks.info())

<class 'pandas.core.frame.DataFrame'>
Index: 1255 entries, 0 to 250
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1255 non-null   datetime64[ns]
 1   open    1255 non-null   float64
 2   high    1255 non-null   float64
 3   low     1255 non-null   float64
 4   close   1255 non-null   float64
 5   volume  1255 non-null   int64
 6   ticker  1255 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(1), object(1)
memory usage: 78.4+ KB

None

In [ ]:
all_stocks_sorted = all_stocks.sort_values(by=['date', 'ticker'])
display(all_stocks_sorted.head())

        date       open       high        low      close    volume ticker
0 2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934   AAPL
0 2018-01-02  1172.0000  1190.0000  1170.5100  1189.0100   2694494   AMZN
0 2018-01-02   177.6800   181.5800   177.5500   181.4200  18151903     FB
0 2018-01-02  1048.3400  1066.9400  1045.2300  1065.0000   1237564   GOOG
0 2018-01-02   196.1000   201.6500   195.4200   201.0700  10966889   NFLX

In [ ]:
highest_volume_rows = all_stocks_sorted.nlargest(7, 'volume')
display(highest_volume_rows)

          date      open      high       low     close     volume ticker
142 2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
53  2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
57  2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
54  2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
182 2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
245 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
212 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

In [ ]:
all_stocks_melted = pd.melt(all_stocks_sorted, id_vars=['date', 'ticker'])
display(all_stocks_melted.head())

        date ticker variable      value
0 2018-01-02   AAPL     open   166.9271
1 2018-01-02   AMZN     open  1172.0000
2 2018-01-02     FB     open   177.6800
3 2018-01-02   GOOG     open  1048.3400
4 2018-01-02   NFLX     open   196.1000