<a href="https://colab.research.google.com/github/YYM89/MSSP607/blob/main/participation6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Lambda
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
import statistics

Mounted at /content/drive

In [3]:
df = pd.read_csv('/content/drive/MyDrive/MSSP607/Assignments/week6/Student Performance Data.csv', encoding='latin1')
display(df)

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low
4,male,group C,some college,standard,76,78,75,229,none,high
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,88,99,95,282,completed,high
996,male,group C,high school,free/reduced,62,55,55,172,none,medium
997,female,group C,high school,free/reduced,59,71,65,195,completed,medium
998,female,group D,some college,standard,68,78,77,223,completed,high
999,female,group D,some college,free/reduced,77,86,86,249,none,high

In [4]:
#creates a new column 'average_score'
df['average_score'] = df[['math score', 'reading score', 'writing score']].apply(lambda row: row.mean(), axis=1)
display(df.head(3))

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect,average_score
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium,72.666667
1,female,group C,some college,standard,69,90,88,247,completed,high,82.333333
2,female,group B,master's degree,standard,90,95,93,278,none,high,92.666667

In [5]:
#creates a 'status' column. If the average_score is 60 or above, the status is 'Pass', otherwise it's 'Fail'.
passing_score = 60
df['status'] = df['average_score'].apply(lambda x: 'Pass' if x >= passing_score else 'Fail')
display(df.head(3))

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect,average_score,status
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium,72.666667,Pass
1,female,group C,some college,standard,69,90,88,247,completed,high,82.333333,Pass
2,female,group B,master's degree,standard,90,95,93,278,none,high,92.666667,Pass

In [9]:
#Combine parental education fields safely
if "EDU_FATHER" in df.columns and "EDU_MOTHER" in df.columns:
    df["PARENT_EDU_COMBO"] = df.apply(
        lambda r: f"{r['EDU_FATHER']}-{r['EDU_MOTHER']}", axis=1
    )
display(df.head(5))

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect,average_score,status
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium,72.666667,Pass
1,female,group C,some college,standard,69,90,88,247,completed,high,82.333333,Pass
2,female,group B,master's degree,standard,90,95,93,278,none,high,92.666667,Pass
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low,49.333333,Fail
4,male,group C,some college,standard,76,78,75,229,none,high,76.333333,Pass